environment: &default
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") { "fe9b5529532e9f57b64902c375abdaff132404652bde6b3a64a1b43cfd18d561bd44d7d009ea678a514b8975d71eeb4ae06c2f7f670cbeba4884dc9750df2fac" } %>
  mail:
    address: <%= ENV.fetch("MAIL_SMTP_ADDRESS") { "" } %>
    port: <%= ENV.fetch("MAIL_SMTP_PORT") { 587 } %>
    domain: <%= ENV.fetch("MAIL_DOMAIN") { "" } %>
    user_name: <%= ENV.fetch("MAIL_USERNAME") { "" } %>
    password: <%= ENV.fetch("MAIL_PASSWORD") { "" } %>
    authentication: <%= ENV.fetch("MAIL_AUTH") { "login" } %>
    enable_starttls_auto: <%= ENV.fetch("MAIL_STARTTLS") { true } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
